### PR TITLE
Restore Python 3 support

### PR DESCRIPTION
**Pull request by clach04**
Use explicit byte literals.

AES encryption padding broken with commit f7e30344c5748e37924c8a4f28522c2bc99a52ee under Python 3.
Python 3 support when using pyaes (instead of Crypto.Cipher.AES) now works.

Tested with Python 2.7.13 and Python 3.6.1.

### CODE REVIEW

**Comment by dony71** [comment]
I have HA 0.59.2 and apply this changes, but still error
Anything I'm missing?


Error while setting up platform broadlink
Traceback (most recent call last):
  File "/root/.homeassistant/deps/lib/python3.4/site-packages/broadlink/__init__.py", line 5, in <module>
    from Crypto.Cipher import AES
ImportError: cannot import name 'AES'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 171, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
  File "/usr/lib/python3.4/asyncio/tasks.py", line 372, in wait_for
    return fut.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/switch/broadlink.py", line 75, in setup_platform
    import broadlink
  File "/root/.homeassistant/deps/lib/python3.4/site-packages/broadlink/__init__.py", line 7, in <module>
    import pyaes
ImportError: No module named 'pyaes'`

**Comment by clach04** [comment]
Yes, you appear to be missing encryption support. Either PyCrypto with AES or the pure python version. This is unrelated to this PR (however I'm glad you found it, I'd assumed this had been merged by now). If you still have problems after resolving dependencies its worth opening a new ticket for Py3 issues.

FYI I'm not sure if python 3.4 is supported by HA.

**Comment by clach04** [comment]
Python3 support is required for projects like Home Assistent https://home-assistant.io/getting-started/

@mjg59 what needs to be done to get this merged (there were no merge conflicts when this PR was posted back in May)?

**Comment by juan11perez** [comment]
good day, I have the same problem as dony71  no clean install. is there a fix?

**Comment by clach04** [comment]
@juan11perez are you seeing this with my branch that this PR is from? If so, that implies the PyCrypto import:

    from Crypto.Cipher import AES

is failing (which would be odd for HA). If this is happening with upstream version, I'd recommend opening a new ticket.
